#!/bin/bash

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other POSIX shell available, try using it by
#       executing "bash /path/to-gradle-wrapper.sh" or "sh /path/to-gradle-wrapper.sh"
#
#   (2) The slurped sed script is necessary to both check for line endings of the
#       file and remove them. The reason why this script is different from the
#       default Gradle wrapper script is to deal with Windows-like line endings
#       (CRLF) on Linux, as well as handling users that work with files in
#       Unix-like line endings on Windows.
#
##############################################################################

basedir=`dirname "$0"`

if [ -z "$JAVA_HOME" ] ; then
  if [ -r /etc/profile.d/java.sh ] ; then
    . /etc/profile.d/java.sh
  fi
fi

if [ -z "$JAVA_HOME" ] ; then
  javaprogram=`which java`
  if [ -z "$javaprogram" ] ; then
    echo "ERROR: JAVA_HOME environment variable is not set and no 'java' command could be found in your PATH."
    echo ""
    echo "Please set the JAVA_HOME variable in your environment to match the"
    echo "location of your Java installation."
    exit 1
  fi
else
  javaprogram="$JAVA_HOME/bin/java"
fi

if [ ! -x "$javaprogram" ] ; then
    echo "ERROR: JAVA_HOME is not defined correctly." >&2
    echo "  We cannot execute $javaprogram" >&2
    exit 1
fi

if [ -z "$CLASSPATH" ] ; then
  CLASSPATH="$basedir"/gradle/wrapper/gradle-wrapper.jar
else
  CLASSPATH="$basedir"/gradle/wrapper/gradle-wrapper.jar:"$CLASSPATH"
fi

export CLASSPATH

exec "$javaprogram" \
  -Dorg.gradle.appname=gradlew \
  -Dorg.gradle.wrapper.properties="$basedir/gradle/wrapper/gradle-wrapper.properties" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
